#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DB1;
    CREATE USER $DB2;

    CREATE DATABASE $DB1;
    CREATE DATABASE $DB2;

    GRANT ALL PRIVILEGES ON DATABASE $DB1 TO $DB1;
    GRANT ALL PRIVILEGES ON DATABASE $DB2 TO $DB2;
EOSQL